collections:
  - name: "gallery"
    label: "Gallery"
    folder: "src/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          fields: [
            { label: "Image", name: "image", widget: "image" },
            { label: "Alt Text", name: "alt", widget: "string" },
            { label: "Caption", name: "caption", widget: "string", required: false }
          ]
        } 